version: "3"

services:
  medmorph_backend:
    image: medmorph_backend
    container_name: medmorph_backend
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - AUTH=http://ec2-3-211-58-180.compute-1.amazonaws.com:8090/auth
      - REALM=backend_app
      - BASE_URL=http://ec2-3-211-58-180.compute-1.amazonaws.com:3000
      - DATA_TRUST_SERVICE=http://ec2-3-211-58-180.compute-1.amazonaws.com:3001