name: Lint and Test

on: [push, pull_request]

jobs:
  verify:
    name: Run Lint and Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - run: npm install

    - run: npm run lint

    - run: npm test
      env:
        CI: true
        REALM: test
        AUTH: http://example.org
